services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./backend/src:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    expose:
      - 8000

  db:
    image: postgres:16.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  # front:
  #   restart: always
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - web
  #   ports:
  #     - 3000:3000

volumes:
  postgres_data:
